name: django-postgres-prod
services:
  backend:
    build: 
      dockerfile: Dockerfile.prod
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER?REQUIRED}
      - DB_PASSWORD=${DB_PASSWORD?REQUIRED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID?REQUIRED}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET?REQUIRED}
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS?REQUIRED}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS?REQUIRED}
      - FRONTEND_URL=${FRONTEND_URL?REQUIRED}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY?REQUIRED}
      - SESSION_COOKIE_DOMAIN=${SESSION_COOKIE_DOMAIN?REQUIRED}
      - DEBUG=false
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - db

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?REQUIRED}
      - POSTGRES_USER=${DB_USER?REQUIRED}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
      - ./postgres_data:/var/lib/postgresql/data
