name: django-postgres-dev
services:
  backend:
    build:
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER?REQUIRED}
      - DB_PASSWORD=${DB_PASSWORD?REQUIRED}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID?REQUIRED}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET?REQUIRED}
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS?REQUIRED}
      - FRONTEND_URL=${FRONTEND_URL?REQUIRED}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY?REQUIRED}
      - DEBUG=true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD?REQUIRED}
      - POSTGRES_USER=${DB_USER?REQUIRED}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql
    