name: django-postgres-dev
services:
  backend:
    build: 
      dockerfile: Dockerfile.dev
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID?REQUIRED}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET?REQUIRED}
      - OATHLIB_INSECURE_TRANSPORT=1
      - ALLOWED_HOSTS=${ALLOWED_HOSTS?REQUIRED}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./createdb.sql:/docker-entrypoint-initdb.d/createdb.sql